INITIAL = [
    ['add_about_window', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_about_window>'],
    ['add_additional_font', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_additional_font>'],
    ['add_annotation', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_annotation>'],
    ['add_area_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_area_series>'],
    ['add_bar_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_bar_series>'],
    ['add_button', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_button>'],
    ['add_candle_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_candle_series>'],
    ['add_character_remap', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_character_remap>'],
    ['add_checkbox', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_checkbox>'],
    ['add_child', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_child>'],
    ['add_collapsing_header',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_collapsing_header>'],
    ['add_color_button', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_color_button>'],
    ['add_color_edit3', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_color_edit3>'],
    ['add_color_edit4', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_color_edit4>'],
    ['add_color_picker3', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_color_picker3>'],
    ['add_color_picker4', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_color_picker4>'],
    ['add_column', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_column>'],
    ['add_columns', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_columns>'],
    ['add_combo', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_combo>'],
    ['add_data', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_data>'],
    ['add_date_picker', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_date_picker>'],
    ['add_debug_window', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_debug_window>'],
    ['add_doc_window', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_doc_window>'],
    ['add_drag_float', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_drag_float>'],
    ['add_drag_float2', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_drag_float2>'],
    ['add_drag_float3', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_drag_float3>'],
    ['add_drag_float4', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_drag_float4>'],
    ['add_drag_int', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_drag_int>'],
    ['add_drag_int2', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_drag_int2>'],
    ['add_drag_int3', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_drag_int3>'],
    ['add_drag_int4', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_drag_int4>'],
    ['add_drag_line', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_drag_line>'],
    ['add_drag_point', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_drag_point>'],
    ['add_drawing', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_drawing>'],
    ['add_dummy', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_dummy>'],
    ['add_error_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_error_series>'],
    ['add_group', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_group>'],
    ['add_heat_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_heat_series>'],
    ['add_hline_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_hline_series>'],
    ['add_image', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_image>'],
    ['add_image_button', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_image_button>'],
    ['add_image_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_image_series>'],
    ['add_indent', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_indent>'],
    ['add_input_float', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_input_float>'],
    ['add_input_float2', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_input_float2>'],
    ['add_input_float3', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_input_float3>'],
    ['add_input_float4', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_input_float4>'],
    ['add_input_int', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_input_int>'],
    ['add_input_int2', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_input_int2>'],
    ['add_input_int3', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_input_int3>'],
    ['add_input_int4', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_input_int4>'],
    ['add_input_text', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_input_text>'],
    ['add_label_text', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_label_text>'],
    ['add_line_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_line_series>'],
    ['add_listbox', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_listbox>'],
    ['add_logger', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_logger>'],
    ['add_managed_columns', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_managed_columns>'],
    ['add_menu', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_menu>'],
    ['add_menu_bar', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_menu_bar>'],
    ['add_menu_item', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_menu_item>'],
    ['add_metrics_window', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_metrics_window>'],
    ['add_next_column', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_next_column>'],
    ['add_node', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_node>'],
    ['add_node_attribute', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_node_attribute>'],
    ['add_node_editor', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_node_editor>'],
    ['add_node_link', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_node_link>'],
    ['add_pie_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_pie_series>'],
    ['add_plot', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_plot>'],
    ['add_popup', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_popup>'],
    ['add_progress_bar', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_progress_bar>'],
    ['add_radio_button', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_radio_button>'],
    ['add_row', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_row>'],
    ['add_same_line', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_same_line>'],
    ['add_scatter_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_scatter_series>'],
    ['add_selectable', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_selectable>'],
    ['add_separator', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_separator>'],
    ['add_shade_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_shade_series>'],
    ['add_simple_plot', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_simple_plot>'],
    ['add_slider_float', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_slider_float>'],
    ['add_slider_float2', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_slider_float2>'],
    ['add_slider_float3', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_slider_float3>'],
    ['add_slider_float4', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_slider_float4>'],
    ['add_slider_int', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_slider_int>'],
    ['add_slider_int2', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_slider_int2>'],
    ['add_slider_int3', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_slider_int3>'],
    ['add_slider_int4', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_slider_int4>'],
    ['add_spacing', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_spacing>'],
    ['add_stair_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_stair_series>'],
    ['add_stem_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_stem_series>'],
    ['add_style_window', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_style_window>'],
    ['add_tab', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_tab>'],
    ['add_tab_bar', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_tab_bar>'],
    ['add_tab_button', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_tab_button>'],
    ['add_table', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_table>'],
    ['add_text', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_text>'],
    ['add_text_point', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_text_point>'],
    ['add_texture', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_texture>'],
    ['add_time_picker', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_time_picker>'],
    ['add_tooltip', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_tooltip>'],
    ['add_tree_node', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_tree_node>'],
    ['add_value', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_value>'],
    ['add_vline_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_vline_series>'],
    ['add_window', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.add_window>'],
    ['bring_draw_command_forward',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.bring_draw_command_forward>'],
    ['bring_draw_command_to_front',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.bring_draw_command_to_front>'],
    ['cleanup_dearpygui', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.cleanup_dearpygui>'],
    ['clear_drawing', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.clear_drawing>'],
    ['clear_item_color', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.clear_item_color>'],
    ['clear_item_style_vars',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.clear_item_style_vars>'],
    ['clear_log', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.clear_log>'],
    ['clear_plot', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.clear_plot>'],
    ['clear_selected_links',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.clear_selected_links>'],
    ['clear_selected_nodes',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.clear_selected_nodes>'],
    ['clear_table', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.clear_table>'],
    ['close_popup', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.close_popup>'],
    ['configure_item', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.configure_item>'],
    ['decref_value', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.decref_value>'],
    ['decrement_texture', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.decrement_texture>'],
    ['delete_annotation', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.delete_annotation>'],
    ['delete_column', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.delete_column>'],
    ['delete_data', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.delete_data>'],
    ['delete_drag_line', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.delete_drag_line>'],
    ['delete_drag_point', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.delete_drag_point>'],
    ['delete_draw_command', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.delete_draw_command>'],
    ['delete_item', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.delete_item>'],
    ['delete_node_link', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.delete_node_link>'],
    ['delete_row', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.delete_row>'],
    ['delete_series', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.delete_series>'],
    ['does_item_exist', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.does_item_exist>'],
    ['draw_arrow', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.draw_arrow>'],
    ['draw_bezier_curve', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.draw_bezier_curve>'],
    ['draw_circle', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.draw_circle>'],
    ['draw_image', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.draw_image>'],
    ['draw_line', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.draw_line>'],
    ['draw_polygon', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.draw_polygon>'],
    ['draw_polyline', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.draw_polyline>'],
    ['draw_quad', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.draw_quad>'],
    ['draw_rectangle', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.draw_rectangle>'],
    ['draw_text', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.draw_text>'],
    ['draw_triangle', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.draw_triangle>'],
    ['enable_docking', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.enable_docking>'],
    ['end', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.end>'],
    ['get_active_window', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_active_window>'],
    ['get_all_items', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_all_items>'],
    ['get_data', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_data>'],
    ['get_dearpygui_version',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_dearpygui_version>'],
    ['get_delta_time', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_delta_time>'],
    ['get_draw_command', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_draw_command>'],
    ['get_drawing_mouse_pos',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_drawing_mouse_pos>'],
    ['get_global_font_scale',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_global_font_scale>'],
    ['get_item_callback', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_item_callback>'],
    ['get_item_callback_data',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_item_callback_data>'],
    ['get_item_children', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_item_children>'],
    ['get_item_configuration',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_item_configuration>'],
    ['get_item_parent', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_item_parent>'],
    ['get_item_rect_max', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_item_rect_max>'],
    ['get_item_rect_min', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_item_rect_min>'],
    ['get_item_rect_size', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_item_rect_size>'],
    ['get_item_type', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_item_type>'],
    ['get_links', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_links>'],
    ['get_log_level', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_log_level>'],
    ['get_main_window_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_main_window_size>'],
    ['get_managed_column_width',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_managed_column_width>'],
    ['get_mouse_drag_delta',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_mouse_drag_delta>'],
    ['get_mouse_pos', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_mouse_pos>'],
    ['get_plot_mouse_pos', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_plot_mouse_pos>'],
    ['get_plot_query_area', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_plot_query_area>'],
    ['get_plot_xlimits', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_plot_xlimits>'],
    ['get_plot_ylimits', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_plot_ylimits>'],
    ['get_selected_links', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_selected_links>'],
    ['get_selected_nodes', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_selected_nodes>'],
    ['get_style_antialiased_fill',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_antialiased_fill>'],
    ['get_style_antialiased_lines',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_antialiased_lines>'],
    ['get_style_button_text_align',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_button_text_align>'],
    ['get_style_child_border_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_child_border_size>'],
    ['get_style_child_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_child_rounding>'],
    ['get_style_circle_segment_max_error',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_circle_segment_max_error>'],
    ['get_style_color_button_position',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_color_button_position>'],
    ['get_style_curve_tessellation_tolerance',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_curve_tessellation_tolerance>'],
    ['get_style_display_safe_area_padding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_display_safe_area_padding>'],
    ['get_style_frame_border_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_frame_border_size>'],
    ['get_style_frame_padding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_frame_padding>'],
    ['get_style_frame_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_frame_rounding>'],
    ['get_style_global_alpha',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_global_alpha>'],
    ['get_style_grab_min_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_grab_min_size>'],
    ['get_style_grab_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_grab_rounding>'],
    ['get_style_indent_spacing',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_indent_spacing>'],
    ['get_style_item_inner_spacing',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_item_inner_spacing>'],
    ['get_style_item_spacing',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_item_spacing>'],
    ['get_style_popup_border_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_popup_border_size>'],
    ['get_style_popup_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_popup_rounding>'],
    ['get_style_scrollbar_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_scrollbar_rounding>'],
    ['get_style_scrollbar_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_scrollbar_size>'],
    ['get_style_selectable_text_align',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_selectable_text_align>'],
    ['get_style_tab_border_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_tab_border_size>'],
    ['get_style_tab_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_tab_rounding>'],
    ['get_style_touch_extra_padding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_touch_extra_padding>'],
    ['get_style_window_border_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_window_border_size>'],
    ['get_style_window_menu_button_position',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_window_menu_button_position>'],
    ['get_style_window_padding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_window_padding>'],
    ['get_style_window_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_window_rounding>'],
    ['get_style_window_title_align',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_style_window_title_align>'],
    ['get_table_data', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_table_data>'],
    ['get_table_item', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_table_item>'],
    ['get_table_selections',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_table_selections>'],
    ['get_theme', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_theme>'],
    ['get_theme_item', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_theme_item>'],
    ['get_total_time', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_total_time>'],
    ['get_value', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_value>'],
    ['get_windows', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.get_windows>'],
    ['incref_value', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.incref_value>'],
    ['insert_column', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.insert_column>'],
    ['insert_row', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.insert_row>'],
    ['is_dearpygui_running',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_dearpygui_running>'],
    ['is_item_activated', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_item_activated>'],
    ['is_item_active', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_item_active>'],
    ['is_item_clicked', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_item_clicked>'],
    ['is_item_container', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_item_container>'],
    ['is_item_deactivated', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_item_deactivated>'],
    ['is_item_deactivated_after_edit',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_item_deactivated_after_edit>'],
    ['is_item_edited', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_item_edited>'],
    ['is_item_focused', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_item_focused>'],
    ['is_item_hovered', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_item_hovered>'],
    ['is_item_shown', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_item_shown>'],
    ['is_item_toggled_open',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_item_toggled_open>'],
    ['is_item_visible', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_item_visible>'],
    ['is_key_down', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_key_down>'],
    ['is_key_pressed', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_key_pressed>'],
    ['is_key_released', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_key_released>'],
    ['is_mouse_button_clicked',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_mouse_button_clicked>'],
    ['is_mouse_button_double_clicked',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_mouse_button_double_clicked>'],
    ['is_mouse_button_down',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_mouse_button_down>'],
    ['is_mouse_button_dragging',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_mouse_button_dragging>'],
    ['is_mouse_button_released',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_mouse_button_released>'],
    ['is_plot_queried', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.is_plot_queried>'],
    ['log', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.log>'],
    ['log_debug', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.log_debug>'],
    ['log_error', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.log_error>'],
    ['log_info', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.log_info>'],
    ['log_warning', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.log_warning>'],
    ['modify_draw_command', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.modify_draw_command>'],
    ['move_item', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.move_item>'],
    ['move_item_down', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.move_item_down>'],
    ['move_item_up', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.move_item_up>'],
    ['open_file_dialog', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.open_file_dialog>'],
    ['render_dearpygui_frame',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.render_dearpygui_frame>'],
    ['reset_xticks', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.reset_xticks>'],
    ['reset_yticks', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.reset_yticks>'],
    ['select_directory_dialog',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.select_directory_dialog>'],
    ['send_draw_command_back',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.send_draw_command_back>'],
    ['send_draw_command_to_back',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.send_draw_command_to_back>'],
    ['set_accelerator_callback',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_accelerator_callback>'],
    ['set_color_map', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_color_map>'],
    ['set_exit_callback', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_exit_callback>'],
    ['set_global_color', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_global_color>'],
    ['set_global_font_scale',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_global_font_scale>'],
    ['set_headers', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_headers>'],
    ['set_individual_color',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_individual_color>'],
    ['set_item_callback', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_item_callback>'],
    ['set_item_callback_data',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_item_callback_data>'],
    ['set_item_color', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_item_color>'],
    ['set_item_style_var', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_item_style_var>'],
    ['set_key_down_callback',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_key_down_callback>'],
    ['set_key_press_callback',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_key_press_callback>'],
    ['set_key_release_callback',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_key_release_callback>'],
    ['set_log_level', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_log_level>'],
    ['set_logger_window_title',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_logger_window_title>'],
    ['set_main_window_pos', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_main_window_pos>'],
    ['set_main_window_resizable',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_main_window_resizable>'],
    ['set_main_window_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_main_window_size>'],
    ['set_main_window_title',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_main_window_title>'],
    ['set_managed_column_width',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_managed_column_width>'],
    ['set_mouse_click_callback',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_mouse_click_callback>'],
    ['set_mouse_double_click_callback',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_mouse_double_click_callback>'],
    ['set_mouse_down_callback',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_mouse_down_callback>'],
    ['set_mouse_drag_callback',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_mouse_drag_callback>'],
    ['set_mouse_move_callback',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_mouse_move_callback>'],
    ['set_mouse_release_callback',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_mouse_release_callback>'],
    ['set_mouse_wheel_callback',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_mouse_wheel_callback>'],
    ['set_plot_xlimits', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_plot_xlimits>'],
    ['set_plot_xlimits_auto',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_plot_xlimits_auto>'],
    ['set_plot_ylimits', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_plot_ylimits>'],
    ['set_plot_ylimits_auto',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_plot_ylimits_auto>'],
    ['set_primary_window', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_primary_window>'],
    ['set_render_callback', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_render_callback>'],
    ['set_resize_callback', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_resize_callback>'],
    ['set_start_callback', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_start_callback>'],
    ['set_style_antialiased_fill',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_antialiased_fill>'],
    ['set_style_antialiased_lines',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_antialiased_lines>'],
    ['set_style_button_text_align',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_button_text_align>'],
    ['set_style_child_border_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_child_border_size>'],
    ['set_style_child_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_child_rounding>'],
    ['set_style_circle_segment_max_error',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_circle_segment_max_error>'],
    ['set_style_color_button_position',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_color_button_position>'],
    ['set_style_curve_tessellation_tolerance',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_curve_tessellation_tolerance>'],
    ['set_style_display_safe_area_padding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_display_safe_area_padding>'],
    ['set_style_frame_border_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_frame_border_size>'],
    ['set_style_frame_padding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_frame_padding>'],
    ['set_style_frame_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_frame_rounding>'],
    ['set_style_global_alpha',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_global_alpha>'],
    ['set_style_grab_min_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_grab_min_size>'],
    ['set_style_grab_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_grab_rounding>'],
    ['set_style_indent_spacing',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_indent_spacing>'],
    ['set_style_item_inner_spacing',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_item_inner_spacing>'],
    ['set_style_item_spacing',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_item_spacing>'],
    ['set_style_popup_border_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_popup_border_size>'],
    ['set_style_popup_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_popup_rounding>'],
    ['set_style_scrollbar_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_scrollbar_rounding>'],
    ['set_style_scrollbar_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_scrollbar_size>'],
    ['set_style_selectable_text_align',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_selectable_text_align>'],
    ['set_style_tab_border_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_tab_border_size>'],
    ['set_style_tab_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_tab_rounding>'],
    ['set_style_touch_extra_padding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_touch_extra_padding>'],
    ['set_style_window_border_size',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_window_border_size>'],
    ['set_style_window_menu_button_position',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_window_menu_button_position>'],
    ['set_style_window_padding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_window_padding>'],
    ['set_style_window_rounding',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_window_rounding>'],
    ['set_style_window_title_align',
     '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_style_window_title_align>'],
    ['set_table_data', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_table_data>'],
    ['set_table_item', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_table_item>'],
    ['set_table_selection', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_table_selection>'],
    ['set_theme', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_theme>'],
    ['set_theme_item', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_theme_item>'],
    ['set_value', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_value>'],
    ['set_vsync', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_vsync>'],
    ['set_xticks', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_xticks>'],
    ['set_yticks', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.set_yticks>'],
    ['setup_dearpygui', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.setup_dearpygui>'],
    ['show_logger', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.show_logger>'],
    ['start_dearpygui', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.start_dearpygui>'],
    ['stop_dearpygui', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.stop_dearpygui>'],
    ['unindent', '<https://hoffstadt.github.io/DearPyGui/api_core.html#dearpygui.core.unindent>'],
    ['child', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.child>'],
    ['collapsing_header', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.collapsing_header>'],
    ['get_drawing_size', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.get_drawing_size>'],
    ['get_item_height', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.get_item_height>'],
    ['get_item_label', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.get_item_label>'],
    ['get_item_tip', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.get_item_tip>'],
    ['get_item_width', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.get_item_width>'],
    ['get_window_pos', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.get_window_pos>'],
    ['group', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.group>'],
    ['hide_item', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.hide_item>'],
    ['managed_columns', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.managed_columns>'],
    ['menu', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.menu>'],
    ['menu_bar', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.menu_bar>'],
    ['node', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.node>'],
    ['node_attribute', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.node_attribute>'],
    ['node_editor', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.node_editor>'],
    ['popup', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.popup>'],
    ['set_drawing_size', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.set_drawing_size>'],
    ['set_item_height', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.set_item_height>'],
    ['set_item_label', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.set_item_label>'],
    ['set_item_name', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.set_item_name>'],
    ['set_item_tip', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.set_item_tip>'],
    ['set_item_width', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.set_item_width>'],
    ['set_window_pos', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.set_window_pos>'],
    ['show_about', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.show_about>'],
    ['show_debug', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.show_debug>'],
    ['show_documentation',
     '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.show_documentation>'],
    ['show_item', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.show_item>'],
    ['show_logger', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.show_logger>'],
    ['show_metrics', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.show_metrics>'],
    ['show_style_editor', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.show_style_editor>'],
    ['tab', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.tab>'],
    ['tab_bar', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.tab_bar>'],
    ['tooltip', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.tooltip>'],
    ['tree_node', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.tree_node>'],
    ['window', '<https://hoffstadt.github.io/DearPyGui/api_simple.html#dearpygui.simple.window>'],
]
